### PR TITLE
Add kotlin dsl

### PR DESCRIPTION
**Pull request by StefMa**
Hey guys 👋 

this will translate all `build file script` into Kotlin...

But Unfortunately I don't know how to translate something like this into "kotlin":
```
[listing.terminal]
----
❯ gradle init
include::{samplesoutputdir}/gradle-init.txt[]
----
```

I wanted to add something like 
```
----
❯ gradle init --dsl kotlin
include::{samplesoutputdir}/gradle-init.txt[]
----
```
But using the `source.multi-language-sample` (tag?) is wrong here IMO.

Is there something like `[listing.terminal-multi-langauge]`? 🙃 
cc @eriwen 

TODOs:
- [x] Update tests
- [x] See question above 👆

### CODE REVIEW

**Comment by eriwen** [comment]
@StefMa Thanks for tackling this!

You'll need to do these 2 things to address your question:
 1) Rebase on latest `master` which upgrades the gradle guides to version 0.13.2
 2) Use these for switchable content:

```
[listing.multi-language-text.lang-groovy]
----
❯ gradle init
include::{samplesoutputdir}/gradle-init.txt[]
----

[listing.multi-language-text.lang-kotlin]
----
❯ gradle init --dsl kotlin
include::{samplesoutputdir}/gradle-init.txt[]
----
```

Basically, `.multi-language-text` mirrors the `.multi-langauge-sample` with 1 important difference: it does not provide tabs. 

Also, why not just use `.multi-language-sample` for this terminal input?

**Comment by StefMa** [comment]
Hi @eriwen 

I'm not aware of all these different tags and tbh I don't know where these come from 🙃 
That was the reason why I have asked.

The `listing.multi-language-text.lang-kotlin` (respo ...lang-groovy) works. But as you say it don't provide tabs - which is bad.

I tried to use `. multi-langauge-sample` but fail :/
The thing is, this output is not a "source". Means if I use `source.multi-langauge-sample,kotlin` it look like this:
bildschirmfoto 2018-06-04 um 15 08 01
As you see the "Starting" and "Gradle Deamon" are purple...

Using `listing.multi-language-sample,kotlin` or `listing.multi-language-sample.lang-kotlin` leads to issues in the UI:
geist_1528117820402

All i want to do is to have 
* tabs
* display content without syntax highlighting...

How can I do that?

**Comment by eriwen** [comment]
There's not currently a way to show tabs outside of a code sample. I could implement this, but I first want to understand why we really need to provide tabs for every block that has Groovy and Kotlin variants?

**Comment by StefMa** [comment]
I fixed the guide overall a little bit.
Hope everything is good now 👌 

While doing it I found out that the tests wasn't running 😅 
I've added the test plugin and fixed the test.
(Beside of adding the Kotlin tests of course).

Oh and BTW.
Your privacy page has moved 
```
// Not working
https://gradle.org/privacy/
// Working
https://gradle.org/privacy
```
Maybe an issue for https://github.com/gradle-guides/gradle-guides-plugin?
Or can you fix that in your backend?

**Comment by eskatos** [comment]
I stumbled upon the same issue as @StefMa when translating the `creating-multi-project-builds` guide: different content present *before* the first code sample where one can switch DSLs makes reading clunky.

Maybe we should consider having a simple switch available on top of each guide so one can choose before starting reading.

Thinking out loud: ideally there's always some visual signal to the reader about which DSL is currently selected even if the page is scrolled down (e.g. after navigating to a subtitle link) or display no sample. Being able to switch from anywhere would be great too.

WDYT @eriwen?

**Comment by eskatos** [comment]
@StefMa the privacy link issue should be fixed now

**Comment by eriwen** [comment]
I think we could consider something toggling the current DSL flavor in the fixed navigation at the top. I'd ask that we not block this conversion on such a thing. I have an idea but I'd like @aweida's help on it later since it'll be very visible.

**Comment by eriwen** [comment]
This LGTM. Do you all agree this is ready to merge?

**Comment by eskatos** [comment]
Not ready to merge, the requirements says Java 7, but if you want to use the Kotlin DSL then the requirement is Java 8. I don't know how to fix this without having what I described above. Any idea @eriwen?

**Comment by StefMa** [comment]
I had a little bit "radical" idea to solve that. 
But that requires that you will ditch the Groovy DSL sometime in the future...

What about to only display only **one** DSL?
Means the whole documentation is either written "for" the Kotlin DSL **or** the Groovy DSL.
There is only **one** single switch at the top of the page (somewhere) where you can either toggle to "Show Kotlin"- or "Show Groovy"- DSL.

The bad thing about the solution is that you don't have a "side by side"-view for the "transition period" from Groovy to Kotlin. Additionally each documentation can contain completely different content. Which have of course negative and positive aspects.

Anyway. Just wanted to share my idea 🙃

**Comment by eskatos** [comment]
Hi @StefMa,
I think we should keep it simple for now and simply spell the difference in requirements, e.g.:

```
* A Java Development Kit (JDK), version 1.7 or better if using the Gradle Groovy DSL, version 1.8 or better if using the Gradle Kotlin DSL (only necessary to run Gradle)
```

**Comment by eskatos** [comment]
Thank you @StefMa!

**Pull request merged**
